### ISSUE TITLE
linux-nonfree: iwlwifi not working

### ISSUE THREAD

**Issue by fps** [guix-nonfree/pkgs#4]
<code>modprobe iwlwifi</code> seems to be a noop, it simply does nothing. Loading the module using <code>insmod</code> directly from the store produces some output in <code>dmesg</code>. The main point is that it seems that the firmware is not found. I guess the <code>linux-nonfree</code> package needs some more love. @andywingo, have you got this working ever?

**Comment by andywingo** [comment]
On Mon 30 Nov 2015 20:50, Florian Paul Schmidt <notifications@github.com> writes:

> modprobe iwlwifi seems to be a noop, it simply does nothing. Loading the
> module using insmod directly from the store produces some output in
> dmesg. The main point is that it seems that the firmware is not found. I
> guess the linux-nonfree package needs some more love. @andywingo, have
> you got this working ever?

The two firmware packages that I made work for me.  I use them on my
thinkpad.

Andy

**Comment by fps** [comment]
OK, I will fiddle a little more. I suppose using the kernel is just as simple as this:

```
(use-modules (gnu) (gnu system nss))

(use-service-modules networking ssh desktop)
(use-package-modules admin xorg certs)

(use-modules (nonfree packages linux-nonfree))
             
(operating-system
  (host-name "cherry")

[...]

  (kernel linux-nonfree)

[...]

  (packages
   (append
    (map
     specification->package
     '("emacs"
       "iwlwifi-firmware-nonfree"
       "xmonad"
       "dmenu"
       "feh"
       "network-manager"))
    %base-packages))
  
  (services
   (cons*
    (lsh-service #:port-number 2222)
    %desktop-services)))
```

Did you perform additional steps to get it to work?

**Comment by andywingo** [comment]
no, you need (firmware (cons iwlwifi-firmware-nonfree %base-firmware)) in your os decl

**Comment by fps** [comment]
Oh, OK, thanks. Will try that and add a wiki page once it works :)

**Comment by fps** [comment]
https://github.com/guix-nonfree/pkgs/wiki/Using-non-libre-kernel-with-iwlwifi
